- build.gradle
- http/boardRestAPI.http
- src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
- src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
- src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
- src/main/java/com/devsplan/ketchup/board/entity/Board.java
- src/main/java/com/devsplan/ketchup/board/entity/BoardAndMember.java
- src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
- src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
- src/main/java/com/devsplan/ketchup/board/service/BoardService.java
- src/main/java/com/devsplan/ketchup/common/Pagenation.java
- src/main/java/com/devsplan/ketchup/common/PagingButton.java
- src/main/java/com/devsplan/ketchup/common/ResponseDTO.java
- src/main/java/com/devsplan/ketchup/config/BeanConfig.java
- src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
- src/main/java/com/devsplan/ketchup/notice/dto/NoticeDTO.java
- src/main/java/com/devsplan/ketchup/notice/entity/Notice.java
- src/main/java/com/devsplan/ketchup/notice/repository/NoticeRepository.java
- src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
- src/main/java/com/devsplan/ketchup/util/FileUtils.java
- src/main/resources/application.yml
- src/test/java/com/devsplan/ketchup/board/BoardRestTests.java
boardDTO, board Entity  boardFileDTO, boardFile Entity생성
> boardDTO, board Entity 생성

- http/boardRestAPI.http
- src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
- src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
- src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
- src/main/java/com/devsplan/ketchup/board/entity/Board.java
- src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
- src/main/java/com/devsplan/ketchup/board/service/BoardService.java
> 0422 4시30분 hjk

- src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
- src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
- src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
- src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
- src/main/java/com/devsplan/ketchup/util/FileUtils.java
- src/test/java/com/devsplan/ketchup/board/BoardRestTests.java
0422-5시30분-hjk
Controller, Service, Repository 생성
Controller, Service, Repository 생성 확인 완료
#3
> [Feature-0422](#3) - board - test코드 생성

- http/scheduleRestAPI.http
- src/main/java/com/devsplan/ketchup/schedule/controller/ScheduleController.java
Jay-20240423-v1
일정 수정, 일정 삭제 http 테스트 완료하였고, 성공적으로 수정 및 삭제됩니다.
수정: 등록한 일정의 skdNo를 Pathvariable로 받아와 다시 setter로 값을 바꾸어 수정하였습니다.
삭제: 삭제 메소드를 실행시키기 전 Java 8부터 지원하는 Optional 래퍼 클래스를 활용하였습니다.
Optional은 Java 8에서 도입된 클래스로, 값이 존재할 수도 있고 존재하지 않을 수도 있는 값을 감싸는 래퍼 클래스이다.
이를 통해 NullPointerException을 방지하고 명시적으로 값이 없음을 나타낼 수 있다.
findFirst() 메소드는 첫번째 요소를 반환하거나 비어있는 경우 Optional.empty()를 반환한다.
이후 Optional.isPresent() 메소드를 사용하여 값이 존재하는지 확인하고, Optional.get() 메소드를 사용하여 값을 가져올 수 있다.
#이슈번호
#18
> [Feature-0423](#3) - schedule - 일정 http crud 테스트 완료

- src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
- src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
- src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
- src/main/java/com/devsplan/ketchup/board/entity/Board.java
- src/main/java/com/devsplan/ketchup/board/entity/BoardAndMember.java
- src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
- src/main/java/com/devsplan/ketchup/board/service/BoardService.java
- src/main/java/com/devsplan/ketchup/member/DepartmentBoard.java
- src/main/java/com/devsplan/ketchup/member/DepartmentDTO.java
- src/main/java/com/devsplan/ketchup/member/Member.java
- src/main/java/com/devsplan/ketchup/member/MemberDTO.java
- src/test/java/com/devsplan/ketchup/Notice/NoticeRestTests.java
- src/test/java/com/devsplan/ketchup/board/BoardRestTests.java
0424-12시30분-hjk -> main
부서별 자료실 게시물 목록조회 test코드 작성
게시물 목록조회 test 성공 
closed #16
> [Feature-0422](#16) - board - 게시물 목록조회 test코드 작성

- src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
- src/main/java/com/devsplan/ketchup/approval/dto/AppLineDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/ApprovalDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/FormDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/RefLineDTO.java
- src/main/java/com/devsplan/ketchup/approval/entity/AppLine.java
- src/main/java/com/devsplan/ketchup/approval/entity/Approval.java
- src/main/java/com/devsplan/ketchup/approval/entity/Form.java
- src/main/java/com/devsplan/ketchup/approval/entity/RefLine.java
- src/main/java/com/devsplan/ketchup/approval/repository/AppLineRepository.java
- src/main/java/com/devsplan/ketchup/approval/repository/ApprovalRepository.java
- src/main/java/com/devsplan/ketchup/approval/repository/RefLineRepository.java
- src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalRestTests.java
0424-4시-20240424seung -> main
Approval 패키지 생성, 기안 등록 서비스 작성( 파일업로드 제외 )
파일 업로드를 제외한 Approval, AppLine, RefLine test메소드 성공 확인
-
> [Feature-0424](#19) - Approval - 기안등록

- http/memberRestAPI.http
- src/main/java/com/devsplan/ketchup/auth/config/WebConfig.java
- src/main/java/com/devsplan/ketchup/auth/config/WebSecurityConfig.java
- src/main/java/com/devsplan/ketchup/auth/filter/CustomAuthenticationFilter.java
- src/main/java/com/devsplan/ketchup/auth/filter/HeaderFilter.java
- src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
- src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthFailureHandler.java
- src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthSuccessHandler.java
- src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthenticationProvider.java
- src/main/java/com/devsplan/ketchup/auth/interceptor/JwtTokenInterceptor.java
- src/main/java/com/devsplan/ketchup/common/AuthConstants.java
- src/main/java/com/devsplan/ketchup/member/controller/AuthController.java
- src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
- src/main/java/com/devsplan/ketchup/member/dto/AuthorityDTO.java
- src/main/java/com/devsplan/ketchup/member/dto/DepDTO.java
- src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
- src/main/java/com/devsplan/ketchup/member/dto/PositionDTO.java
- src/main/java/com/devsplan/ketchup/member/dto/TokenDTO.java
- src/main/java/com/devsplan/ketchup/member/entity/Authority.java
- src/main/java/com/devsplan/ketchup/member/entity/Dep.java
- src/main/java/com/devsplan/ketchup/member/entity/Member.java
- src/main/java/com/devsplan/ketchup/member/entity/Position.java
- src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
- src/main/java/com/devsplan/ketchup/member/service/MemberService.java
> [Feature-0424](#25) - member - DTO,ENTITY 등록

- src/main/java/com/devsplan/ketchup/auth/model/DetailsUser.java
- src/main/java/com/devsplan/ketchup/auth/model/service/DetailsService.java
- src/main/java/com/devsplan/ketchup/member/entity/Member.java
- src/main/java/com/devsplan/ketchup/member/service/MemberService.java
(확인 후 지워주세요)
ex) member ENTITY 수정하였습니다
#25
> [Feature-0424](#25) - member - ENTITY 수정

- http/mailRestAPI.http
- src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
- src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
- src/main/java/com/devsplan/ketchup/mail/dto/MailFileDTO.java
- src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
- src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
- src/main/java/com/devsplan/ketchup/mail/entity/MailFile.java
- src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
- src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
- src/test/java/com/devsplan/ketchup/mail/MailRestTests.java
ex) 0424-6시30분-pde -> main
ex) 메일 등록, 조회 테스트 코드 작성
ex) 메일 관련 데이터가 DB에 등록되고, 사번을 넣고 조회를 하면 해당 메일이 조회된다.
#이슈번호
#31  #32
> [Feature-0424](#31 #32) - 메일 - 메일 등록, 조회 테스트

- src/main/java/com/devsplan/ketchup/approval/dto/AppFileDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/ApprovalDTO.java
- src/main/java/com/devsplan/ketchup/approval/entity/AppFile.java
- src/main/java/com/devsplan/ketchup/approval/repository/AppFileRepository.java
- src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalRestTests.java
seung -> main
등록에 파일 업로드 로직 추가
일단은 파일 업로드 로직만 추가하고 파일 업로드 제외한 나머지 동작하는건 확인했습니다.
추후 파일 업로드 테스트 필요합니다.
#19
> [Feature-0424](#19) - 기안등록  - 파일업로드 추가 

- src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
- src/main/java/com/devsplan/ketchup/board/entity/Board.java
- src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
- src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
- src/main/java/com/devsplan/ketchup/board/service/BoardService.java
- src/main/resources/application.yml
- src/test/java/com/devsplan/ketchup/board/BoardRestTests.java
- upload-dir/testFile.txt
0425-5시30분-hjk -> main
게시물 등록 test 추가, 게시물 목록조회 시 페이징 되도록 test코드 추가
부서별 자료실 게시물 등록 테스트 성공
부서별 자료실 게시물 페이징 후 목록조회 테스트 성공
closed #38 
closed #4
> [Feature-0425](#4, #38) - board - 게시물 등록 test코드, 게시물 목록 페이징 처리 추가 

- src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
- src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
- src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
- src/test/java/com/devsplan/ketchup/mail/MailRestTests.java
ex) 0426-1시10분-pde -> main
ex) 메일 발송 취소, 메일 삭제 기능 테스트 코드를 작성했습니다.
- 메일 발송 취소가 성공하면 DB에서 발송 여부 데이터가 'Y'로 변경됩니다.
- 메일 삭제가 성공하면 DB에서 삭제 여부 데이터가 'Y'로 변경됩니다.
#43 #45
> [Feature-0426](#43 #45) - 메일 - 발송 취소, 메일 삭제

- src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
- src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
- src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
- src/test/java/com/devsplan/ketchup/mail/MailRestTests.java
> Revert "[Feature-0426](#43 #45) - 메일 - 발송 취소, 메일 삭제"

- src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
- src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
> [Feature-0426] - 메일 - 파일 수정

- src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
- src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
- src/main/java/com/devsplan/ketchup/board/entity/Board.java
- src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
- src/main/java/com/devsplan/ketchup/board/service/BoardService.java
- src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
- src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
- src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
- src/main/java/com/devsplan/ketchup/util/FileUtils.java
- src/main/resources/application.yml
- src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
- src/test/java/com/devsplan/ketchup/mail/MailRestTests.java
- upload-dir/testFile.txt
0426-6시-hjk -> main
부서별 자료실 게시물 등록 첨부파일 추가 등록 test코드 생성
게시물 첨부파일 등록 성공(resources 하위 폴더에 저장됨)
- src 외부에도 파일 저장되는 이슈 수정예정
#30
> [Feature-0426](#30) - board - 부서별 자료실 게시물 등록 첨부파일 등록 test코드 생성

- src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
- src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
- src/main/java/com/devsplan/ketchup/board/dto/BoardFileDTO.java
- src/main/java/com/devsplan/ketchup/board/entity/Board.java
- src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
- src/main/java/com/devsplan/ketchup/board/service/BoardService.java
- src/main/java/com/devsplan/ketchup/common/ResponseDTO.java
- src/main/java/com/devsplan/ketchup/util/FileUtils.java
- src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
0428-2시30분-hjk -> main
-BoardRestTests -> BoardControllerTests, BoardServiceTests 로 controller, service로 test코드 추가
-BoardControllerTests 부서별 자료실 게시물 등록, 수정, 삭제 test코드 생성
-BoardServiceTests 첨부파일 등록, 수정 test 코드 생성 및 수정
-게시물 삭제 시 첨부파일 삭제 
첨부파일 생성 및 삭제 test 성공
controller 게시물 등록, 수정, 삭제 test 성공
closed #46 #47 #54
> [Feature-0422](#46 #47 #54) - board - 부서별 자료실 게시물 등록,수정,삭제 test코드 생성 및 수정

- src/main/java/com/devsplan/ketchup/common/ScheduleBuilder.java
- src/main/java/com/devsplan/ketchup/schedule/entity/Schedule.java
- src/main/java/com/devsplan/ketchup/schedule/service/ScheduleService.java
- src/test/java/com/devsplan/ketchup/schedule/ScheduleRestTests.java
Jay-20240429-v1
부서별 일정을 먼저 조회한 뒤, 해당 일정을 수정할 수 있습니다.
정상적으로 일성이 수정됩니다.
#이슈번호
#61
> [Feature-0429](#61) - schedule - 부서별 일정 수정 테스트

- http/approvalRestAPI.http
- src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
- src/main/java/com/devsplan/ketchup/approval/dto/ApprovalDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/ApprovalSelectDTO.java
- src/main/java/com/devsplan/ketchup/approval/entity/AppLine.java
- src/main/java/com/devsplan/ketchup/approval/entity/Approval.java
- src/main/java/com/devsplan/ketchup/approval/entity/ApprovalSelect.java
- src/main/java/com/devsplan/ketchup/approval/entity/Form.java
- src/main/java/com/devsplan/ketchup/approval/entity/RefLine.java
- src/main/java/com/devsplan/ketchup/approval/repository/AppLineRepository.java
- src/main/java/com/devsplan/ketchup/approval/repository/ApprovalSelectRepository.java
- src/main/java/com/devsplan/ketchup/approval/repository/RefLineRepository.java
- src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
- src/main/java/com/devsplan/ketchup/board/service/BoardService.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalControllerTests.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalRestTests.java
ex) seung -> main
목록조회 서비스 메소드 & 서비스테스트코드 
#44
>  [Feature-0428](#44) - 전자결재 목록조회 - service

- http/memberRestAPI.http
- src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
- src/main/java/com/devsplan/ketchup/member/controller/TestController.java
- src/main/java/com/devsplan/ketchup/member/entity/Dep.java
- src/main/java/com/devsplan/ketchup/util/TokenUtils.java
ex) 240429-hoo-3-> main
ex) 로그인 이후 사원의 부서번호 조회
ex) LV1 권한만 접근 가능한 TestController에서 추가하여 1번 사원으로만 접근 가능합니다.
#72
> [Feature-0429] - {TestController} 로그인 이후 토큰의 클레임에서 부서정보 조회 

- http/boardRestAPI.http
- src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
- src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
- src/main/java/com/devsplan/ketchup/board/service/BoardService.java
- src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
- src/main/java/com/devsplan/ketchup/notice/dto/NoticeDTO.java
- src/main/java/com/devsplan/ketchup/notice/entity/Notice.java
- src/main/java/com/devsplan/ketchup/notice/repository/NoticeRepository.java
- src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
- src/test/java/com/devsplan/ketchup/Notice/NoticeRestTests.java
- src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
- src/test/java/com/devsplan/ketchup/notice/service/NoticeServiceTests.java
0430-9시10분-hjk -> main
공지사항 DTO, Entity 생성
공지사항 serviceTests 등록, 수정, 삭제 코드 작성
entity, DTO 필드, 생성자 등 생성
closed #57
>  [Feature-0430](#57) - notice- 공지사항 DTO, Entity 생성, service test코드 작성

- src/main/java/com/devsplan/ketchup/notice/dto/NoticeFileDTO.java
- src/main/java/com/devsplan/ketchup/notice/entity/NoticeFile.java
- src/main/java/com/devsplan/ketchup/notice/repository/NoticeFileRepository.java
0430-9시45분-hjk -> main
fileDTO, filerepository fileEntity 생성
생성 성공
>  [Feature-0430] - notice- 게시글 파일 class수정

- http/memberRestAPI.http
- src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthenticationProvider.java
- src/main/java/com/devsplan/ketchup/common/Authority.java
- src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
- src/main/java/com/devsplan/ketchup/member/service/MemberService.java
- src/main/java/com/devsplan/ketchup/util/TokenUtils.java
- src/test/java/com/devsplan/ketchup/member/MemberRestTest.java
ex) 240430-hoo-1 -> main
ALL직급 삭제, 직급수정 테스트코드, http 추가
ALL 직급 선언이 잘못되어있어 삭제하였으며 대표는 LV3 의 권한으로 진행해주시면 감사하겠습니다!
#82
> [Feature-0430] - ALL직급 삭제, 직급수정 추가

- http/mailRestAPI.http
- src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
- src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
- src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
- src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
- src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
- src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
- src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
- src/test/java/com/devsplan/ketchup/mail/controller/MailControllerTests.java
- src/test/java/com/devsplan/ketchup/mail/service/MailRestTests.java
ex) 0430-2시40분-pde -> main
- 메일 등록, 조회 컨트롤러 테스트를 추가했습니다.
메일 관련 데이터를 등록하고 조회하는 기능 테스트가 성공합니다.
#85 #86
> [Feature-0430](#85 #86) - 메일 - 메일 등록, 조회 테스트

- http/approvalRestAPI.http
- src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
- src/main/java/com/devsplan/ketchup/approval/dto/AppInputDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/AppUpdateDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/ApprovalDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/ApprovalSelectDTO.java
- src/main/java/com/devsplan/ketchup/approval/entity/AppMember.java
- src/main/java/com/devsplan/ketchup/approval/entity/Approval.java
- src/main/java/com/devsplan/ketchup/approval/entity/ApprovalSelect.java
- src/main/java/com/devsplan/ketchup/approval/repository/AppLineRepository.java
- src/main/java/com/devsplan/ketchup/approval/repository/ApprovalSelectRepository.java
- src/main/java/com/devsplan/ketchup/approval/repository/FormRepository.java
- src/main/java/com/devsplan/ketchup/approval/repository/RefLineRepository.java
- src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalControllerTests.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalRestTests.java
0502seung -> main
#이슈번호
#97 #83
> [Feature-0502](#97 #83) - 전자결재상신, 양식 조회

- src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
- src/main/java/com/devsplan/ketchup/approval/dto/AppInputDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/AppLineAndMemberDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/AppUpdateDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/ApprovalSelectDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/MemberDTO.java
- src/main/java/com/devsplan/ketchup/approval/dto/RefLineAndMemberDTO.java
- src/main/java/com/devsplan/ketchup/approval/entity/AppLine.java
- src/main/java/com/devsplan/ketchup/approval/entity/AppLineAndMember.java
- src/main/java/com/devsplan/ketchup/approval/entity/AppMember.java
- src/main/java/com/devsplan/ketchup/approval/entity/ApprovalSelect.java
- src/main/java/com/devsplan/ketchup/approval/entity/Member.java
- src/main/java/com/devsplan/ketchup/approval/entity/RefLineAndMember.java
- src/main/java/com/devsplan/ketchup/approval/repository/ApprovalSelectRepository.java
- src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalControllerTests.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalServiceTests.java
0503seung-> main
컨트롤러 테스트 추가 밑 기안 목록 조회 페이징, 조회 엔티티 추가했습니다
#118 #119
> [Feature-0503](#118 #119) - 기안목록 조회, controller test

- src/test/java/com/devsplan/ketchup/board/service/BoardServiceTests.java
- src/test/java/com/devsplan/ketchup/notice/service/NoticeServiceTests.java
0503-10시55분-hjk -> main
부서별 자료실 목록조회 service test 코드 수정
공지 목록조회 service test 코드 수정
부서별 자료실 목록조회 test 성공
공지 목록조회 test 성공
#55 #59
> [Feature-0503] - board, notice - 부서별 자료실, 공지 service test 코드 수정

- http/memberRestAPI.http
- src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
- src/test/java/com/devsplan/ketchup/member/MemberTest.java
ex) 240503-hoo-1 -> main
ex)  사원 상세 조회 추가하였습니다.
ex)이상없음.
#122
> [Feature-0503] - {MemberController, MemberTest,Member} 사원 상세조회 추가 

- http/approvalRestAPI.http
- src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
- src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalServiceTests.java
0503seung -> main
http 에 restapi 요청 테스트 작성했습니다~
👍🏿
> [Feature-0503](# ) -  approval rest api 테스트 - http 파일 추가

- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
- src/test/java/com/devsplan/ketchup/mail/service/MailServiceTests.java
> 메일 조회 오류 수정

- build.gradle
- http/memberRestAPI.http
- src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
- src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
- src/main/java/com/devsplan/ketchup/member/service/MemberService.java
- src/main/resources/application.yml
240503-hoo-3 -> main
개인메일로 인증번호 발송 기능을 추가하였습니다.
입력한 사원의 개인메일로 인증번호가 발송되었습니다.
#135
> [Feature-0503] - 입력한 사원의 개인메일로 인증번호 발송

- src/main/java/com/devsplan/ketchup/rsc/dto/RscDTO.java
- src/main/java/com/devsplan/ketchup/rsc/entity/Rsc.java
- src/main/java/com/devsplan/ketchup/rsc/repository/RscRepository.java
- src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
- src/test/java/com/devsplan/ketchup/rsc/RscServiceTests.java
0506-3시-pde -> main
등록한 자원을 수정하고 삭제할 수 있는 코드를 추가했습니다.
자원을 수정하고 삭제하는 테스트가 성공합니다.
#141
> [Feature-0506](#141) - 자원 관리 -  자원 수정, 삭제 테스트

- src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
- src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
- src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
- src/main/java/com/devsplan/ketchup/mail/entity/MailFile.java
- src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
- src/main/java/com/devsplan/ketchup/rsc/entity/Rsc.java
- src/test/java/com/devsplan/ketchup/mail/service/MailServiceTests.java
0506-6시-pde -> main
엔티티 setter 사용 -> builder 사용
메일 기능 정상 작동
> [Feature-0506] - 메일 - 메일 엔티티 setter 사용 수정

- http/mailRestAPI.http
- http/rscRestAPI.http
- src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
- src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
- src/main/java/com/devsplan/ketchup/rsc/dto/RscDTO.java
- src/main/java/com/devsplan/ketchup/rsc/entity/Rsc.java
- src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
- src/test/java/com/devsplan/ketchup/mail/MailControllerTests.java
- src/test/java/com/devsplan/ketchup/mail/MailServiceTests.java
- src/test/java/com/devsplan/ketchup/rsc/RscControllerTests.java
- src/test/java/com/devsplan/ketchup/rsc/RscServiceTests.java
0507-12시20분-pde -> main
- 자원을 등록하고, 조회하고, 수정, 삭제할 수 있는 데이터를 넘겨줄 수 있게 controller를 추가했습니다.
- 자원이 등록되고, 조회되고, 수정, 삭제됩니다.
#144
> [Feature-0507](#144) - 자원 - 자원 관리 controller 테스트 및 작성

- src/main/java/com/devsplan/ketchup/auth/handler/CustomAuthSuccessHandler.java
ex)240508-hoo-2 -> main
ex) 토큰에 status 추가했습니다
#152
> [Feature-0508] -  {CustomAuthSuccessHandler} 내용 수정

- src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
- src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
0508-6시-pde -> main
컨트롤러 ResponseEntity 수정
컨트롤러에 작성한 결과대로 반환됩니다.
> [Feature-0508] - 메일 - 메일 컨트롤러 수정

- src/main/java/com/devsplan/ketchup/reserve/entity/Reserve.java
0508-9시-pde -> main
엔티티 조인 컬럼 변경
> [Feature-0508] 자원 - 자원 엔티티 수정

- src/main/java/com/devsplan/ketchup/reserve/repository/ReserveRepository.java
- src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
- src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
0509-10시30분-pde -> main
- 자원 수정, 삭제 시 해당 자원의 예약 일정을 삭제하고 해당 자원의 예약자한테 메일을 보냅니다.
- 자원 수정 시 해당 자원의 일정을 확인하여 있으면 일정을 삭제하고 메일을 보냅니다.
- 작원 삭제 시 해당 자원의 일정을 확인하여 있으면 일정을 삭제하고 메일을 보냅니다.
#141
> [Feature-0509](#141) - 자원 관리 - 자원 수정 삭제 시 예약 삭제, 메일 전송

- src/test/java/com/devsplan/ketchup/rsc/RscServiceTests.java
> [Bug-0509] - 자원 관리 - 자원 테스트 오류 수정

- src/main/java/com/devsplan/ketchup/auth/filter/JwtAuthorizationFilter.java
- src/main/java/com/devsplan/ketchup/util/TokenUtils.java
ex)240509-hoo-1 -> main
ex) 토큰 클레임 부서명 추가
사용하실때 depName으로 꺼내주세요
#159
> [Feature-0509] - {TokenUtils} 토큰 클레임 부서명 추가 

- src/main/java/com/devsplan/ketchup/member/service/MemberService.java
- src/main/java/com/devsplan/ketchup/util/TokenUtils.java
- src/main/resources/application.yml
ex) 240509-hoo-1 -> main
파일 저장 경로 수정하였습니다.
ex) 프로젝트 명이 일치해야 하며 두 프로젝트가 같은경로에 있어야합니다.
#164
> [Feature-0509] - {application.yml} 파일저장경로 수정

- src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
- src/main/java/com/devsplan/ketchup/notice/entity/Notice.java
- src/main/java/com/devsplan/ketchup/notice/repository/NoticeRepository.java
- src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
0511-11시50분-hjk -> main
공지 목록조회 db목록 전체 반환 수정
전체 공지 목록이 반환되는것 확인됨
#80
> [Feature-0511](#80) - notice - 공지 목록조회 service메소드 수정

- src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
- src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
0512-10시22분-hjk -> main
공지 수정, 공지삭제 service, controller 메소드 수정
권한관련 제한 코드 수정 후 공지 수정, 삭제 성공 
#59 #58
> [Feature-0512](#58 #59) - notice - 공지 수정, 삭제 메소드 수정

- src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
- src/main/java/com/devsplan/ketchup/mail/dto/ReceiverDTO.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
- src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
0514-1시20분-pde -> main
- 메일 등록 수정, 받은 메일 조회시 수신자 읽음 여부 추가
- 받은 메일 조회 시 읽음 여부가 출력됩니다.
#179
> [Feature-0514](#179) - 메일 - 메일 등록, 받은 메일 수신자 읽음 여부 추가 수정

- src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
- src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
- src/main/java/com/devsplan/ketchup/member/repository/MemberRepository.java
- src/main/java/com/devsplan/ketchup/member/service/MemberService.java
ex) 240514-hoo-1-> main
ex) 페이징없는 전체사원조회 구현했습니다.
#183
> [Feature-0514] - {MemberController} 페이징없는 사원전체조회 추가 #183

- src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
- src/main/java/com/devsplan/ketchup/mail/entity/Receiver.java
- src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
0515-6시30분-pde -> main
- 메일 수신자 읽음 여부 상태 변경
- 메일 수신자 읽음이 null에서 클릭 시간으로 데이터가 입력됩니다.
#182
> [Feature-0515](#182) - 메일 - 메일 읽음 상태 변경

- http/approvalRestAPI.http
- src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
- src/main/java/com/devsplan/ketchup/approval/dto/ApprovalCountDTO.java
- src/main/java/com/devsplan/ketchup/approval/repository/ApprovalRepository.java
- src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalControllerTests.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalServiceTests.java
0516 seung -> main
카테고리별 문서 수를 보여주는 로직입니다.
성공적으로 갯수 카운팅 되는것 확인했습니다.
#187
> [Feature-0516](#187) - 카테고리별 문서 수

- build.gradle
- http/memberRestAPI.http
- src/main/java/com/devsplan/ketchup/common/Authority.java
- src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
- src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
- src/main/java/com/devsplan/ketchup/member/repository/DepRepository.java
- src/main/java/com/devsplan/ketchup/member/repository/PositionRepository.java
- src/main/java/com/devsplan/ketchup/member/service/MemberService.java
ex) 240517-hoo-1->main
부서조회/직급조회 추가
부서조회/직급조회 추가하였으며, MemberDTO의 memberName에 유효성검사를 실시하였습니다.
#189
> [Feature-0517 - {MemberController} 부서조회/직급조회 추가

- src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
- src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
0517seung -> main
기안 상신시 받아오는 List가 비어있을때 발생하던 에러를 위해 controller에 몇가지 추가했습니다.
받아오는 데이터 확인되었고, 등록도 성공적으로 되는거 확인했습니다.
#97
> [Feature-0517](#97) - 기안상신 - 기안상신할때 받아오는 List가 없을때 처리

- src/main/java/com/devsplan/ketchup/common/ResponseDTO.java
- src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
0517-5시-pde -> main
- 메일 내용, 수신자, 파일을 하나의 메소드로 저장되게했습니다.
- 메일 정보가 없을 때의 유효성을 점검하는 코드를 작성했습니다.
- 메일이 전송됩니다.
> [Feature-0517](issue 번호) - 메일 - 메일 전송 코드 업데이트

- src/main/java/com/devsplan/ketchup/mail/controller/MailController.java
- src/main/java/com/devsplan/ketchup/mail/dto/MailDTO.java
- src/main/java/com/devsplan/ketchup/mail/entity/Mail.java
- src/main/java/com/devsplan/ketchup/mail/repository/MailFileRepository.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
0520-10시-pde -> main
- 검색어 조건을 수정했습니다.
- MailDTO, ENTITY에 이전 메일 코드를 추가했습니다.
- 메일 조회 시 파일 조회를 추가했습니다.
- 메일 목록에서 제목으로 통해 검색을 할 수 있습니다.
- 이전 코드가 추가되어 데이터가 출력됩니다.
- 메일 상세 조회 시 메일 파일도 같이 출력됩니다.
#197
> [Feature-0520](#197) - 메일 - 메일 작성 코드 업데이트

- http/memberRestAPI.http
- src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
- src/main/java/com/devsplan/ketchup/member/dto/MemberDTO.java
- src/main/java/com/devsplan/ketchup/member/entity/Member.java
- src/main/java/com/devsplan/ketchup/member/service/MemberService.java
- src/main/resources/application.yml
ex) 240520-hoo-1 -> main
사원 정보 수정 추가
사원정보 수정시 이미지파일을 수정할때와 수정하지 않을때 모두 수정 가능합니다.
#199
> [Feature-0520] - {MemberController, MemberService} 사원정보 수정 #199

- src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
- src/main/java/com/devsplan/ketchup/board/repository/BoardRepository.java
- src/main/java/com/devsplan/ketchup/board/service/BoardService.java
- src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
- src/main/java/com/devsplan/ketchup/notice/dto/NoticeFileDTO.java
- src/main/java/com/devsplan/ketchup/notice/entity/NoticeFile.java
- src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
0522-5시33분-hjk -> main
게시물 상세조회 이전, 다음글 이동
게시물 상세조회 이전글 이동 성공, 다음글 이동 성공
closed #209
> [Feature-0522](#209) - boardService - 게시물 상세조회 이전, 다음글 이동

- src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
- src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
> [Feature-0522](issue 번호) - 기능명 - 자원 수정, 조회 권한 수정

- src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
- src/main/java/com/devsplan/ketchup/board/entity/BoardFile.java
- src/main/java/com/devsplan/ketchup/board/service/BoardService.java
- src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
- src/main/java/com/devsplan/ketchup/notice/repository/NoticeRepository.java
- src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
0522-8시17분-hjk -> main
공지 상세조회(이전, 다음글 이동), 공지 상세조회(파일 삭제)
공지 상세조회(이전, 다음글) 이동
공지 상세조회(파일 삭제) 성공
#78
> [Feature-0522](#78) - notice- 공지 상세조회(이전, 다음글 이동), 공지 상세조회(파일 삭제)

- src/main/java/com/devsplan/ketchup/notice/controller/NoticeController.java
- src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
0523-11시15분-hjk -> main
공지 목록조회 수정
공지 목록조회 페이징 수정 성공
#59 #171
> [Feature-0523](#59 #171) - notice - 공지 목록조회 수정

- src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
- src/main/java/com/devsplan/ketchup/approval/dto/AppFileDTO.java
- src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
(확인 후 지워주세요)
0523seung -> main
modelMapper 자동 변환과정에서 생기던 오류 때문에 dto 에 필드 추가했습니다.
사진파일 두개 이상 업로드 시 문제가 생기던 부분 해결된것 확인했습니다.
#19
> [Feature-0523](#19) - 기안등록 - dto ->entity 변환과정 에러 수정

- http/rscRestAPI.http
- src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
- src/main/java/com/devsplan/ketchup/rsc/repository/RscRepository.java
- src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
0524-10시10분-pde -> main
- 자원 페이징 
- 자원 페이징
> [Feature-0524](issue 번호) - Resources - 자원 페이징 추가

- src/main/java/com/devsplan/ketchup/board/controller/BoardController.java
- src/main/java/com/devsplan/ketchup/board/dto/BoardDTO.java
- src/main/java/com/devsplan/ketchup/board/entity/Board.java
- src/main/java/com/devsplan/ketchup/board/service/BoardService.java
- src/main/java/com/devsplan/ketchup/comment/controller/CommentController.java
- src/main/java/com/devsplan/ketchup/comment/dto/CommentDTO.java
- src/main/java/com/devsplan/ketchup/comment/entity/Comment.java
- src/main/java/com/devsplan/ketchup/comment/repository/CommentRepository.java
- src/main/java/com/devsplan/ketchup/comment/service/CommentService.java
- src/main/java/com/devsplan/ketchup/notice/service/NoticeService.java
- src/main/resources/application.yml
0524-10시50분-hjk -> main
게시물 댓글 dto, entity 생성
게시물 댓글 dto, entity 생성(기존 코드에 영향 없음)
closed #218
> [Feature-0524](#218) - comment- 게시물 댓글 dto, entity 생성

- src/main/java/com/devsplan/ketchup/reserve/controller/ReserveController.java
- src/main/java/com/devsplan/ketchup/reserve/dto/ReserveDTO.java
- src/main/java/com/devsplan/ketchup/reserve/entity/Reserve.java
- src/main/java/com/devsplan/ketchup/reserve/service/ReserveService.java
- src/main/resources/application.yml
- src/test/java/com/devsplan/ketchup/reserve/ReserveServiceTests.java
Jay-20240524-v2
- 자원예약 엔티티에 필드값으로 memberName을 추가하였습니다.
- 빌더패턴에도 추가된 memberName을 추가할 수 있도록 수정하였습니다.
등록단계에서 입력받은 예약자의 성명은 화면에서 출력하여 UX를 향상시켰습니다.
#이슈번호
#229
> [Feature-MMDD](#229) - Reserve - 자원예약 엔티티 수정

- http/memberRestAPI.http
- src/main/java/com/devsplan/ketchup/member/controller/MemberController.java
- src/main/java/com/devsplan/ketchup/member/service/MemberService.java
- src/main/resources/application.yml
240524-hoo-2 -> main
ex) 부서 수정, 부서삭제 구현하였습니다.
ex) 이상없습니다. 해당부서 사원이 없을경우만 삭제 가능합니다.
#231
> [Feature-0524] - {MemberController} 부서 수정, 부서삭제 

- src/main/java/com/devsplan/ketchup/approval/controller/ApprovalController.java
- src/main/java/com/devsplan/ketchup/approval/repository/ApprovalSelectRepository.java
- src/main/java/com/devsplan/ketchup/approval/service/ApprovalService.java
- src/test/java/com/devsplan/ketchup/approval/ApprovalServiceTests.java
0524seung -> main
기존 완료 상태만 보이던 수신 참조 문서에서 대기, 진행, 완료, 반려 문서까지 조회 가능 하도록 로직 수정했습니다.
목록조회 테스트 성공확인했습니다.
#44
> [Feature-0524]() - 전자결재 목록조회 - 수신참조 문서 조회 로직 수정

- src/main/java/com/devsplan/ketchup/comment/dto/CommentDTO.java
- src/main/java/com/devsplan/ketchup/comment/entity/Comment.java
- src/main/java/com/devsplan/ketchup/comment/service/CommentService.java
0528-4시12분-hjk -> main
댓글 dto, entity 수정
댓글 dto, entity 수정 후 이상 없음
closed #220
> [Feature-0528](#220) - board -댓글 dto, entity 수정

- src/main/java/com/devsplan/ketchup/mail/repository/MailRepository.java
- src/main/java/com/devsplan/ketchup/mail/repository/ReceiverRepository.java
- src/main/java/com/devsplan/ketchup/mail/service/MailService.java
- src/main/java/com/devsplan/ketchup/rsc/controller/RscController.java
- src/main/java/com/devsplan/ketchup/rsc/repository/RscRepository.java
- src/main/java/com/devsplan/ketchup/rsc/service/RscService.java
0529-12시-pde -> main
- 자원을 조회할 때 권한을 부서 코드에서 부서 이름으로 변경했습니다.
- 자원 조회 시 권한을 잘 부여합니다.
> [Feature-0529] Mail/Resource - 자원 권한 부서 코드에서 이름으로 수정, 주석 제거
